# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
