# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworkApp', '0002_auto_20170608_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
