
version: '2'
services:


  # Postgres database
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: ./env
    expose:
      - "5432"

  # Django web server
  web:
    build: ./web
    ports:
      - "3000:8008"
    env_file: ./env
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./web/socialNetwork/static:/static
    working_dir: /data/web/socialNetwork/
    command: /data/web/run_web.sh


  nginx:
    restart: always
    build: ./nginx/
    ports:
    - "8001:8001"
    volumes_from:
    - web
    links:
    - web

  #Data Backup
  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgres
    command: "true"
