# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworkApp', '0003_auto_20170608_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
