# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworkApp', '0004_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
